apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-services
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/kchetty-secops/kubernetes.git
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/kchetty-secops/kubernetes.git
        targetRevision: HEAD
        path: '{{path}}/base'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
