apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: datadog-secret
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "datadog/api-key"
        objectType: "secretsmanager"